hbhr/admin/routes.py
from flask import render_template, request, Blueprint, flash
from flask_security import current_user, roles_accepted
from hbhr.models import User, Service
from hbhr import log, db, user_datastore
from hbhr.admin.forms import ServiceForm

admin = Blueprint('admin', __name__)


@admin.route("/admin")
@roles_accepted('admin')
def home():
    return render_template('admin/admin.html', title='Admin')


@admin.route("/admin/services/<int:service_id>/edit", methods=['GET'])
@roles_accepted('admin')
def edit_service(service_id):
    service = Service.query.get_or_404(service_id)
    form = ServiceForm()
    form.name.data = service.name
    form.description.data = service.description
    return render_template('admin/service_edit.html', service=service, form=form)


@admin.route("/admin/services/", methods=['POST'])
@roles_accepted('admin')
def add_service():
    form = ServiceForm()
    if form.validate_on_submit():
        service = Service(name=form.name.data,
                          description=form.description.data)
        db.session.add(service)
        db.session.commit()
        return render_template('admin/service_row.html', service=service)
    return "Error encountered while adding a service."


@admin.route("/admin/services/<int:service_id>", methods=['DELETE'])
@roles_accepted('admin')
def delete_service(service_id):
    # Get the service with the given ID or return a 404 error if not found
    service = Service.query.get_or_404(service_id)

    # Delete the service
    db.session.delete(service)

    # Commit the changes to the database
    db.session.commit()

    return ''


@admin.route("/admin/services/<int:service_id>/status", methods=['PUT'])
@roles_accepted('admin')
def toggle_service_status(service_id):
    # Get the service with the given ID or return a 404 error if not found
    service = Service.query.get_or_404(service_id)

    # Toggle the status of the service (i.e. change from active to inactive or vice versa)
    service.toggle_status()

    # Commit the changes to the database
    db.session.commit()

    # Render the template for the updated service row
    return render_template('admin/service_row.html', service=service)


@admin.route("/admin/services/<int:service_id>", methods=['GET', 'PUT'])
@roles_accepted('admin')
def get_service(service_id):
    # if PUT - update the service
    # if GET - update was cancelled, so return what was there before
    service = Service.query.get_or_404(service_id)
    form = ServiceForm()
    if form.validate_on_submit():
        service.name = form.name.data
        service.description = form.description.data
        db.session.commit()
        return render_template('admin/service_row.html', service=service)
    return render_template('admin/service_row.html', service=service)


@admin.route("/admin/services")
@roles_accepted('admin')
def services():

    services = Service.query.all()
    form = ServiceForm()

    return render_template('admin/services.html', title='Edit services', services=services, form=form)


# @admin.route("/admin/setup")
# def setup():

#     chu = User.query.filter(User.username == 'vchu').first()
#     log.info(chu)

#     user_datastore.create_role(name='admin', description='Administrator')
#     log.info("created admin role")

#     admin_role = user_datastore.find_role("admin")
#     log.info("found admin role")

#     user_datastore.add_role_to_user(chu, admin_role)
#     log.info("added admin role to chu")

#     # user_datastore.activate_user(chu)

#     db.session.commit()
#     log.info("committed to db")

#     return render_template('admin/setup.html', title='Admin')

hbhr/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, abort, current_app
from flask_security import current_user, login_required, AnonymousUser
from hbhr import log, db
from hbhr.models import Service, Business, Address, Phone
from hbhr.main.forms import BusinessForm, AddressForm, PhoneForm, LinkServicesForm
from hbhr.utils import save_thumbnail, get_search_seed
import phonenumbers 
from sqlalchemy import or_, text
from bleach import clean
import paginate

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    log.debug("home")
    services = Service.query.filter_by(status=Service.ACTIVE).order_by(Service.id.asc()).all()
    top_services = []
    for n in range(0,current_app.config['TOP_SERVICES']):
        top_services.append(services.pop(0))
    return render_template('index.html', title='Welcome', top_services=top_services, services=services)


@main.route("/about")
def about():
    return render_template('about.html', title='About HSHR')

@main.route("/help")
def help():
    return render_template('help.html', title='Help - Your Questions Answered')

@main.route("/privacy")
def privacy():
    return render_template('privacy.html', title='Privacy policy')

@main.route("/tos")
def tos():
    return render_template('TOS.html', title='Terms of service')


@main.route('/search')
def search():
    search_terms = request.args.get('q')

    if search_terms:
        search_terms = clean(search_terms.lower())
    else:
        search_terms = ""

    log.debug(f"search: {search_terms}")

    page = request.args.get('page') or ''
    
    if page.isdigit():
        page = int(page)
    else:
        page = 1

    sql = text(f'''
        select setseed({get_search_seed()});
        select b.*
        from (
            SELECT DISTINCT b.* 
            FROM public.business AS b
            JOIN public.service_business AS sb ON b.id = sb.business_id
            JOIN public.service AS s ON sb.service_id = s.id
            where (s.name ilike '%{search_terms}%' or s.description ilike '%{search_terms}%' or b.name ilike '%{search_terms}%')
                and b.status = 'active' and s.status = 'active'
        ) AS b
        ORDER BY random()
        ;
    ''')

    businesses = db.session.query(Business).from_statement(sql).all()

    businesses = paginate.Page(businesses, page=page, items_per_page=current_app.config['RESULTS_PER_PAGE'],
                               url_maker=lambda p: f"{url_for('main.search')}?q={search_terms}&page={p}")

    # Create links for pages
    pager_links = businesses.pager(link_attr={ 'class':'button is-primary is-light is-small' },
                                   curpage_attr={ 'class':'button is-primary is-small' })

    # Display something as a serch term on the template, and also make the header load
    if not search_terms:
        search_terms = 'Everything'

    return render_template('search_results.html', businesses=businesses, search_terms=search_terms, title='Search results', pager_links=pager_links)


@main.route('/service/<int:service_id>')
def service(service_id):
    # Get service with provided ID from the database or return a 404 error if it doesn't exist.
    service = Service.query.get_or_404(service_id)

    # If the service is not active, return a page with no businesses and the service information.
    if not service.is_active():
        return render_template('search_results.html', businesses=None, service=service)

    # Create an empty list to hold the businesses associated with the service.
    businesses = []

    page = request.args.get('page') or ''
    
    if page.isdigit():
        page = int(page)
    else:
        page = 1

    sql = text(f'''
        select setseed({get_search_seed()});
        select b.*
        from (
            SELECT DISTINCT b.* 
            FROM public.business AS b
            JOIN public.service_business AS sb ON b.id = sb.business_id
            JOIN public.service AS s ON sb.service_id = s.id
            where s.id = {service_id} and b.status = 'active'
        ) AS b
        ORDER BY random()
        ;
    ''')

    businesses = db.session.query(Business).from_statement(sql).all()

    businesses = paginate.Page(businesses, page=page, items_per_page=current_app.config['RESULTS_PER_PAGE'],
                               url_maker=lambda p: f"{url_for('main.service', service_id=service_id)}?&page={p}")

    # Create links for pages
    pager_links = businesses.pager(link_attr={ 'class':'button is-primary is-light is-small' },
                                   curpage_attr={ 'class':'button is-primary is-small' })

    # Return a page displaying the businesses associated with the service and the service information.
    return render_template('search_results.html', businesses=businesses, service=service, title=service.name, description=service.description, pager_links=pager_links)


@main.route('/others')
def others():
    all_bus = Business.query.all()

    businesses = []

    for business in all_bus:
        if business.is_active() and not business.services:
           businesses.append(business)
    
    return render_template('search_results.html', businesses=businesses, others=True, title='Uncategorized businesses')

################
### BUSINESS ###
################


@main.route("/business/new", methods=['GET', 'POST'])
@login_required
def new_business():
    form = BusinessForm()

    log.info(f"{current_user.id}: new_business")
    
    if form.validate_on_submit():
        business = Business(name=form.name.data, email=form.email.data, webpage=form.webpage.data, description=form.description.data)
        business.set_url(form.name.data)
        business.add_member(user=current_user, role=Business.OWNER)
        db.session.add(business)
        db.session.commit()

        log.info(f"{current_user.id}: Created business {business.id}")

        flash(f'Your business {business.name} has been created', 'success')
        return redirect(url_for('main.business', business_url=business.url))

    return render_template('business_new.html', title='New business',
                           form=form)

@main.route("/business/<int:business_id>/edit", methods=['GET', 'POST'])
@login_required
def edit_business(business_id):
    log.info(f"{current_user.id}: edit_business id: {business_id}")

    business = Business.query.get_or_404(business_id)
    if not (current_user.is_owner(business_id) or current_user.has_role('admin')):
        flash("You don't have the permission to edit this business. Check with the business owner or admin.","warning")
        return redirect(url_for('main.business', business_url=business.id))

    form = BusinessForm(business_id=business.id)

    if form.validate_on_submit():
        if form.image_file.data:
            image_file = save_thumbnail(form.image_file.data)
            business.image_file = image_file
        business.name = form.name.data
        if form.url.data is None:
            business.set_url(form.name.data)
        else:
            business.set_url(form.url.data)
        business.email = form.email.data
        business.webpage = form.webpage.data
        business.description = form.description.data
        db.session.commit()
        flash('Your business has been updated!', 'success')
        log.info(f"{current_user.id}: edit_business id: {business_id} - update success")
        return redirect(url_for('main.business', business_url=business.url))
    elif request.method == 'GET':
        form.name.data = business.name
        form.email.data = business.email
        form.url.data = business.url
        form.webpage.data = business.webpage
        form.description.data = business.description

    image_file = url_for('static', filename='profile_pics/' + business.image_file)

    return render_template('business_edit.html', title='Manage business',
                           form=form, business_id=business_id)


@main.route("/business/<string:business_url>", methods=['GET'])
def business(business_url):
    business = Business.query.filter_by(url=business_url).first()
    if not business:
        return render_template('errors/404.html')
    
    if business.status == business.INACTIVE:
        if isinstance(current_user, AnonymousUser) or not (current_user.is_owner(business.id) or current_user.has_role('admin')):
            return render_template('errors/404.html')
        flash(f'Your business is hidden. Click the green "Publish business" button below when ready.', 'warning')

    return render_template('business.html', title=business.name, business=business, description=business.description)

@main.route("/business/<int:business_id>/status", methods=['PUT'])
@login_required
def toggle_business_status(business_id):
    # Get the business with the given ID or return a 404 error if not found
    business = Business.query.get_or_404(business_id)

    # Check if the user is authorized to make this change
    if not (current_user.is_owner(business.id) or current_user.has_role('admin')):
        return render_template('errors/404.html')
    
    # Toggle the status of the service (i.e. change from active to inactive or vice versa)
    business.toggle_status()
    
    # Commit the changes to the database
    db.session.commit()

    log.info(f"{current_user.id}: toggle_business_status id: {business_id} - update success")
    
    # Render the template for the updated service row
    return render_template('business_status_button.html', business=business)


#################
### ADDRESSES ###
#################

@main.route("/business/<int:business_id>/address/new", methods=['GET', 'POST'])
@login_required
def add_address(business_id):
    business = Business.query.get_or_404(business_id)
    # return the form for the address input
    form = AddressForm()
    if form.validate_on_submit():
        address = Address(address=form.address.data, city=form.city.data, state=form.state.data, zip=form.zip.data)

hbhr/users/routes.py
from hbhr import db
from hbhr.users.forms import UpdateAccountForm
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_security import current_user, login_required, AnonymousUser
from hbhr.utils import save_thumbnail
from hbhr.models import User

users = Blueprint('users', __name__)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_thumbnail(form.picture.data)
            current_user.image_file = picture_file
        current_user.set_username(form.username.data)
        current_user.email = form.email.data
        current_user.display_name = form.display_name.data
        current_user.notes = form.notes.data
        current_user.location = form.location.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.display_name.data = current_user.display_name
        form.notes.data = current_user.notes
        form.location.data = current_user.location
    return render_template('account.html', title='Account',
                           form=form, user=current_user)


@users.route("/dashboard", methods=['GET'])
@login_required
def dashboard():
    return render_template('dashboard.html', title='Dashboard',
                           user=current_user)


@users.route("/user/<string:username>", methods=['GET'])
def profile(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        return render_template('errors/404.html')

    return render_template('profile_page.html', user=user, title=user.display_name, description=user.notes)

hbhr/templates/business.html
{% extends "layout.html" %}
{% block content %}
<div class="section">
    <div class="columns">
        <div class="column is-offset-1-desktop is-one-fifth">
            {% include 'business_header.html' %}
        </div>

        <div class="column is-three-fifths-desktop">
            <div class="content">
                {% include 'messages.html' %}
                <h1 class="title is-2">{{ business.name }}</h1>
                <hr>
                {% include 'services_list.html' %}
                
                {% if business.webpage %}
                <p><span class="icon is-small mr-3">
                    <i class="fa fa-arrow-up-right-from-square"></i>
                </span> <a href="{{ business.webpage }}" target="_blank">{{ business.webpage }}</a></p>
                {% endif %}
                <p><span class="icon is-small mr-3">
                    <i class="fa fa-envelope"></i>
                </span> <a href="mailto:{{ business.email }}">{{ business.email }}</a></p>

                <div id="phones">
                {% if business.phones %}
                    {% for phone in business.phones %}
                    {% include 'phone.html' %}
                    {% endfor %}
                {% endif %}
                </div>

                <div id="addresses">
                {% if business.addresses %}
                    {% for address in business.addresses %}
                    {% include 'address.html' %}
                    {% endfor %}
                {% endif %}
                </div>
                <br><br>

                {% if business.description %}
                {{ business.description|markdown }}
                {% endif %}
                
            </div>
            <br>

            {% if current_user.is_authenticated and (current_user.is_owner(business.id) or current_user.has_role('admin')) %}
            <!-- Main container -->
            <nav class="level">
                    <!-- Left side -->
                <div class="level-left">

                </div>

                <!-- Right side -->
                <div class="level-right">
                    <p class="level-item">
                        <a class="button is-small is-rounded" hx-get="{{ url_for('main.add_phone', business_id=business.id) }}"
                            hx-target="#add-edit-info" 
                            hx-swap="innerHTML"
                            hx-trigger="click" _="on click toggle .is-active on #add-edit-info">
                            Add phone number
                        </a>
                    </p>
                    <p class="level-item">
                        <a class="button is-small is-rounded" hx-get="{{ url_for('main.add_address', business_id=business.id) }}"
                            hx-target="#add-edit-info" 
                            hx-swap="innerHTML"
                            hx-trigger="click" _="on click toggle .is-active on #add-edit-info">
                            Add address
                        </a>
                    </p>
                    <p class="level-item">
                        <a class="button is-small is-rounded" hx-get="{{ url_for('main.edit_services', business_id=business.id) }}"
                            hx-target="#add-edit-info" 
                            hx-swap="innerHTML"
                            hx-trigger="click" _="on click toggle .is-active on #add-edit-info">
                            List services
                        </a>
                    </p>
                    <p class="level-item">
                        <a class="button is-small is-rounded" href="{{ url_for('main.edit_business', business_id=business.id) }}">
                            Edit business
                        </a>
                    </p>
                    {% include 'business_status_button.html' %}
                </div>
            </nav>
            <div id="add-edit-info" class="modal">
                
            </div>

            {% endif %}

            <aside class="menu">
                <p class="menu-label">
                    Members
                </p>
                <ul class="menu-list">
                    {% for member in business.members %}
                    <li>
                        <a href="{{ url_for('users.profile', username=member.username ) }}">
                        <div class="columns is-vcentered">
                            <div class="column is-narrow is-hidden-mobile">
                                <figure class="image is-32x32">
                                    <img class="is-rounded" src="{{ url_for('static', filename='profile_pics/' + member.image_file) }}">
                                </figure>
                            </div>
                            <div class="column">
                                <span>{{ member.display_name }}</span>
                            </div>
                        </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </aside>
            
        </div>
        <div class="column is-one-fifth-desktop is-hidden-tablet-only"></div>
    </div>
</div>
{% endblock content %}

hbhr/templates/business_status_button.html
{% if business.status == business.ACTIVE %}
{# Deactivate #}
<p class="level-item" id="status-toggle">
    <a class="button is-warning is-small is-rounded" 
        hx-put="{{ url_for('main.toggle_business_status', business_id=business.id) }}" 
        hx-target="#status-toggle"
        hx-trigger="click"
        hx-swap="outerHTML swap:1s">
        Hide business
    </a>
</p>
{% else %}
{# Activate #}
<p class="level-item" id="status-toggle">
    <a class="button is-success is-small is-rounded" 
        hx-put="{{ url_for('main.toggle_business_status', business_id=business.id) }}" 
        hx-target="#status-toggle"
        hx-trigger="click"
        hx-swap="outerHTML swap:1s">
        Publish business
    </a>
</p>
{% endif %}

hbhr/templates/index.html
{% extends "layout.html" %}
{% block content %}
<!-- Header for big screen -->
<section>
    <div class="hero is-primary is-small is-hidden-mobile">
        <div class="hero-body">
            <br>
            <div class="container has-text-centered">
                <h1 class="title is-1 is-family-secondary pb-3">
                    Homebirth Support Hampton Roads
                </h1>
                <h2 class="subtitle is-5 is-uppercase ">
                    Helping families find the best way to bring their babies into the world
                </h2>
            </div>
            <br><br>
        </div>
    </div>
    <!-- Header for phone screen-->
    <div class="hero is-primary is-small is-hidden-tablet">
        <br>
        <div class="hero-body">
            <div class="container has-text-centered">
                <h2 class="title is-3 is-family-secondary pb-3">
                    Homebirth Support Hampton Roads
                </h2>
                <h3 class="subtitle is-6 is-uppercase">
                    Helping families find the best way to bring their babies into the world
                </h3>
            </div>
            <br>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="has-text-centered content">
            {% include 'messages.html' %}
            <h3 class="title is-3 is-uppercase">Directory of services</h3>
            <hr>
        </div>
        <div id="categories" class="columns is-multiline">
            {% for service in top_services %}
            <div class="column is-one-third-desktop is-half-tablet">
                <div class="block has-text-centered">

                    <h5 class="subtitle is-5 is-uppercase" _="on click toggle .is-hidden-mobile on next .content">
                        {{ service.name }}
                    </h5>
                    <div class="content is-hidden-mobile">
                        <hr>
                        <p>{{ service.description }}</p>
                        <a href="{{ url_for('main.service', service_id=service.id) }}"
                            class="button is-link is-outlined is-rounded">List providers</a>
                    </div>
                    <br>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <figure class="image">
                        <img class="is-rounded"
                            src="{{ url_for('static', filename='img/luma-pimentel-1vnB2l7j3bY-unsplash.jpg') }}"
                            alt="Newborn baby feet">
                    </figure>
                </div>
                <div class="column">
                    <div class="content mx-5">
                        {% if current_user.is_authenticated %}
                        <p class="title">
                            List your business
                        </p>
                        <p class="subtitle">
                            Create your business page and have it included in our directory.
                        </p>
                        <a class="button is-link" href="{{ url_for('main.new_business') }}">Create your business</a>
                        {% else %}
                        <p class="title">
                            List your business
                        </p>
                        <p class="subtitle">
                            Create an account and get your business included in our directory to help expectant families
                            find your services.
                        </p>
                        <a class="button is-link" href="{{ url_for('security.register') }}">Start here</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="has-text-centered content">
            <h4 class="subtitle is-4 is-uppercase">Other services</h4>
            <hr>
        </div>
        <div class="columns is-multiline">
            {% for service in services %}
            <div class="column is-one-quarter-desktop is-one-third-tablet">
                <div class="block has-text-centered">
                    <a href="{{ url_for('main.service', service_id=service.id) }}">
                        <h6 class="subtitle is-6 is-uppercase">
                            {{ service.name }}
                        </h6>
                    </a>
                </div>
            </div>
            {% endfor %}
            <div class="column is-one-quarter-desktop is-one-third-tablet">
                <div class="block has-text-centered">
                    <a href="{{ url_for('main.others') }}">
                        <h6 class="subtitle is-6 is-uppercase">
                            Uncategorized Businesses
                        </h6>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

hbhr/templates/layout.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>

    {% include 'navbar.html' %}


    {% block content %}{% endblock %}

    {% include 'footer.html' %}

</body>

</html>

hbhr/templates/navbar.html
<!-- Navigation bar -->
<nav class="main-nav navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="{{ url_for('main.home') }}">
        <h5 class="is-5 is-uppercase is-family-secondary">HSHR</h5>
      </a>
      <div role="button" class="navbar-burger"
        _="on click toggle .is-active on me then toggle .is-active on .navbar-menu">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item">
          <form name="search" method="GET" action="{{ url_for('main.search') }}">
            <div class="field has-addons">
              <div class="control">
                <input class="input" type="search" name="q" placeholder="I'm looking for...">
              </div>
              <div class="control">
                <button class="button is-link" type="submit">
                  <span class="icon"><i class="fa fa-search"></i></span>
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="navbar-end">
        
        <!-- <a class="navbar-item" href="#about">
          <span class="icon">
            <i class="fa fa-pencil"></i>
          </span>
          <span>Blog</span>
        </a>
        <a class="navbar-item" href="#services">
          <span class="icon">
            <i class="fa fa-bars"></i>
          </span>
          <span>Birth stories</span>
        </a> -->

        {% if current_user.has_role('admin') %}
        <a class="navbar-item" href="{{ url_for('admin.home') }}">
            Admin
        </a>
        {% endif %}
        
        {% if current_user.is_authenticated %}
          {% if current_user.businesses %}
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Businesses</a>
            <div class="navbar-dropdown">
              {% for business in current_user.businesses %}
              <a class="navbar-item" href="{{ url_for('main.business', business_url=business.url) }}">
                {{ business.name }}
              </a>
              {% endfor %}
              <hr class="navbar-divider">
              <a class="navbar-item" href="{{ url_for('main.new_business') }}">
                Add a business
              </a>
            </div>
          </div>
          {% else %}
          <a class="navbar-item" href="{{ url_for('main.new_business') }}">
            Add a business
          </a>
          {% endif %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
              <div class="mx-1 is-hidden-touch">
                <figure class="image is-32x32 avatar-small">
                  <img class="is-rounded"
                    src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
                </figure>
              </div>
              <span>{{ current_user.display_name }}</span>
          </a>
          <div class="navbar-dropdown">
            <a class="navbar-item" href="{{ url_for('users.dashboard') }}">
              Dashboard
            </a>
            <a class="navbar-item" href="{{ url_for('users.account') }}">
              Account
            </a>
            <a class="navbar-item" href="{{ url_for('security.logout') }}">
              Log out
            </a>
          </div>
        </div>

        {% else %}
        <div class="buttons">
          <a class="button is-link" href="{{ url_for('security.register') }}">
            <strong>Sign up</strong>
          </a>
          <a class="button is-primary" href="{{ url_for('security.login') }}">
            Log in
          </a>
        </div>

        {% endif %}
      </div>
    </div>
  </div>
</nav>