hbhr/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, abort, current_app
from flask_security import current_user, login_required, AnonymousUser
from hbhr import log, db
from hbhr.models import Service, Business, Address, Phone
from hbhr.main.forms import BusinessForm, AddressForm, PhoneForm, LinkServicesForm
from hbhr.utils import save_thumbnail, get_search_seed
import phonenumbers 
from sqlalchemy import or_, text
from bleach import clean
import paginate

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    log.debug("home")
    services = Service.query.filter_by(status=Service.ACTIVE).order_by(Service.id.asc()).all()
    top_services = []
    for n in range(0,current_app.config['TOP_SERVICES']):
        top_services.append(services.pop(0))
    return render_template('index.html', title='Welcome', top_services=top_services, services=services)


@main.route("/about")
def about():
    return render_template('about.html', title='About HSHR')

@main.route("/help")
def help():
    return render_template('help.html', title='Help - Your Questions Answered')

@main.route("/privacy")
def privacy():
    return render_template('privacy.html', title='Privacy policy')

@main.route("/tos")
def tos():
    return render_template('TOS.html', title='Terms of service')


@main.route('/search')
def search():
    search_terms = request.args.get('q')

    if search_terms:
        search_terms = clean(search_terms.lower())
    else:
        search_terms = ""

    log.debug(f"search: {search_terms}")

    page = request.args.get('page') or ''
    
    if page.isdigit():
        page = int(page)
    else:
        page = 1

    sql = text(f'''
        select setseed({get_search_seed()});
        select b.*
        from (
            SELECT DISTINCT b.* 
            FROM public.business AS b
            JOIN public.service_business AS sb ON b.id = sb.business_id
            JOIN public.service AS s ON sb.service_id = s.id
            where (s.name ilike '%{search_terms}%' or s.description ilike '%{search_terms}%' or b.name ilike '%{search_terms}%')
                and b.status = 'active' and s.status = 'active'
        ) AS b
        ORDER BY random()
        ;
    ''')

    businesses = db.session.query(Business).from_statement(sql).all()

    businesses = paginate.Page(businesses, page=page, items_per_page=current_app.config['RESULTS_PER_PAGE'],
                               url_maker=lambda p: f"{url_for('main.search')}?q={search_terms}&page={p}")

    # Create links for pages
    pager_links = businesses.pager(link_attr={ 'class':'button is-primary is-light is-small' },
                                   curpage_attr={ 'class':'button is-primary is-small' })

    # Display something as a serch term on the template, and also make the header load
    if not search_terms:
        search_terms = 'Everything'

    return render_template('search_results.html', businesses=businesses, search_terms=search_terms, title='Search results', pager_links=pager_links)


@main.route('/service/<int:service_id>')
def service(service_id):
    # Get service with provided ID from the database or return a 404 error if it doesn't exist.
    service = Service.query.get_or_404(service_id)

    # If the service is not active, return a page with no businesses and the service information.
    if not service.is_active():
        return render_template('search_results.html', businesses=None, service=service)

    # Create an empty list to hold the businesses associated with the service.
    businesses = []

    page = request.args.get('page') or ''
    
    if page.isdigit():
        page = int(page)
    else:
        page = 1

    sql = text(f'''
        select setseed({get_search_seed()});
        select b.*
        from (
            SELECT DISTINCT b.* 
            FROM public.business AS b
            JOIN public.service_business AS sb ON b.id = sb.business_id
            JOIN public.service AS s ON sb.service_id = s.id
            where s.id = {service_id} and b.status = 'active'
        ) AS b
        ORDER BY random()
        ;
    ''')

    businesses = db.session.query(Business).from_statement(sql).all()

    businesses = paginate.Page(businesses, page=page, items_per_page=current_app.config['RESULTS_PER_PAGE'],
                               url_maker=lambda p: f"{url_for('main.service', service_id=service_id)}?&page={p}")

    # Create links for pages
    pager_links = businesses.pager(link_attr={ 'class':'button is-primary is-light is-small' },
                                   curpage_attr={ 'class':'button is-primary is-small' })

    # Return a page displaying the businesses associated with the service and the service information.
    return render_template('search_results.html', businesses=businesses, service=service, title=service.name, description=service.description, pager_links=pager_links)


@main.route('/others')
def others():
    all_bus = Business.query.all()

    businesses = []

    for business in all_bus:
        if business.is_active() and not business.services:
           businesses.append(business)
    
    return render_template('search_results.html', businesses=businesses, others=True, title='Uncategorized businesses')

################
### BUSINESS ###
################


@main.route("/business/new", methods=['GET', 'POST'])
@login_required
def new_business():
    form = BusinessForm()

    log.info(f"{current_user.id}: new_business")
    
    if form.validate_on_submit():
        business = Business(name=form.name.data, email=form.email.data, webpage=form.webpage.data, description=form.description.data)
        business.set_url(form.name.data)
        business.add_member(user=current_user, role=Business.OWNER)
        db.session.add(business)
        db.session.commit()

        log.info(f"{current_user.id}: Created business {business.id}")

        flash(f'Your business {business.name} has been created', 'success')
        return redirect(url_for('main.business', business_url=business.url))

    return render_template('business_new.html', title='New business',
                           form=form)

@main.route("/business/<int:business_id>/edit", methods=['GET', 'POST'])
@login_required
def edit_business(business_id):
    log.info(f"{current_user.id}: edit_business id: {business_id}")

    business = Business.query.get_or_404(business_id)
    if not (current_user.is_owner(business_id) or current_user.has_role('admin')):
        flash("You don't have the permission to edit this business. Check with the business owner or admin.","warning")
        return redirect(url_for('main.business', business_url=business.id))

    form = BusinessForm(business_id=business.id)

    if form.validate_on_submit():
        if form.image_file.data:
            image_file = save_thumbnail(form.image_file.data)
            business.image_file = image_file
        business.name = form.name.data
        if form.url.data is None:
            business.set_url(form.name.data)
        else:
            business.set_url(form.url.data)
        business.email = form.email.data
        business.webpage = form.webpage.data
        business.description = form.description.data
        db.session.commit()
        flash('Your business has been updated!', 'success')
        log.info(f"{current_user.id}: edit_business id: {business_id} - update success")
        return redirect(url_for('main.business', business_url=business.url))
    elif request.method == 'GET':
        form.name.data = business.name
        form.email.data = business.email
        form.url.data = business.url
        form.webpage.data = business.webpage
        form.description.data = business.description

    image_file = url_for('static', filename='profile_pics/' + business.image_file)

    return render_template('business_edit.html', title='Manage business',
                           form=form, business_id=business_id)


@main.route("/business/<string:business_url>", methods=['GET'])
def business(business_url):
    business = Business.query.filter_by(url=business_url).first()
    if not business:
        return render_template('errors/404.html')
    
    if business.status == business.INACTIVE:
        if isinstance(current_user, AnonymousUser) or not (current_user.is_owner(business.id) or current_user.has_role('admin')):
            return render_template('errors/404.html')
        flash(f'Your business is hidden. Click the green "Publish business" button below when ready.', 'warning')

    return render_template('business.html', title=business.name, business=business, description=business.description)

@main.route("/business/<int:business_id>/status", methods=['PUT'])
@login_required
def toggle_business_status(business_id):
    # Get the business with the given ID or return a 404 error if not found
    business = Business.query.get_or_404(business_id)

    # Check if the user is authorized to make this change
    if not (current_user.is_owner(business.id) or current_user.has_role('admin')):
        return render_template('errors/404.html')
    
    # Toggle the status of the service (i.e. change from active to inactive or vice versa)
    business.toggle_status()
    
    # Commit the changes to the database
    db.session.commit()

    log.info(f"{current_user.id}: toggle_business_status id: {business_id} - update success")
    
    # Render the template for the updated service row
    return render_template('business_status_button.html', business=business)


#################
### ADDRESSES ###
#################

@main.route("/business/<int:business_id>/address/new", methods=['GET', 'POST'])
@login_required
def add_address(business_id):
    business = Business.query.get_or_404(business_id)
    # return the form for the address input
    form = AddressForm()
    if form.validate_on_submit():
        address = Address(address=form.address.data, city=form.city.data, state=form.state.data, zip=form.zip.data)

hbhr/templates/security/change_password.html
{% extends "layout.html" %}
{% from "security/_macros.html" import prop_next %}

{% block content %}
<div class="section">
    <div class="container">
        <br><br>
        <div class="columns">
            <div class="column is-hidden-touch"></div>
            <div class="column is-three-fifths-desktop">
                {% include 'messages.html' %}
                <div class="box is-fullwidth">
                    <form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
                        {{ change_password_form.hidden_tag() }}
                        <fieldset>
                            <legend class="is-size-3 mb-3">Change your password</legend>
                            {% if active_password %}
                            <div class="field">
                                {{ change_password_form.password.label(class="label") }}

                                {% if change_password_form.password.errors %}
                                <p class="control has-icons-left">
                                    {{ change_password_form.password(class="input is-danger",
                                    autocomplete="current-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                <div class="help is-danger">
                                    {% for error in change_password_form.password.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ change_password_form.password(class="input", autocomplete="current-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                            {% else %}
                            <h3>You do not currently have a password - this will add one.</h3>
                            {% endif %}
                            <div class="field">
                                {{ change_password_form.new_password.label(class="label") }}

                                {% if change_password_form.new_password.errors %}
                                <p class="control has-icons-left">
                                    {{ change_password_form.new_password(class="input is-danger",
                                    autocomplete="new-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                <div class="help is-danger">
                                    {% for error in change_password_form.new_password.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ change_password_form.new_password(class="input", autocomplete="new-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                            <div class="field">
                                {{ change_password_form.new_password_confirm.label(class="label") }}
                                {% if change_password_form.new_password_confirm.errors %}
                                <p class="control has-icons-left">
                                    {{ change_password_form.new_password_confirm(class="input is-danger",
                                    autocomplete="current-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                <div class="help is-danger">
                                    {% for error in change_password_form.new_password_confirm.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ change_password_form.new_password_confirm(class="input",
                                    autocomplete="new-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="field mt-4">
                            <div class="control">
                                {{ change_password_form.submit(class="button is-primary") }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="column is-hidden-touch"></div>
        </div>
    </div>
</div>

{% endblock %}

hbhr/templates/security/forgot_password.html
{% extends "layout.html" %}
{% block content %}
<div class="section">
    <div class="container">
        <br><br>
        <div class="columns">
            <div class="column is-hidden-touch"></div>
            <div class="column is-three-fifths-desktop">
                {% include 'messages.html' %}
                <div class="box is-fullwidth">
                    <form action="{{ url_for_security('forgot_password') }}" method="post" name="forgot_password_form">
                        {{ forgot_password_form.hidden_tag() }}
                        <fieldset>
                            <legend class="is-size-3 mb-3">{{ legend }}</legend>
                            <div class="field">
                                {{ forgot_password_form.email.label(class="label") }}
                                {% if forgot_password_form.email.errors %}
                                {{ forgot_password_form.email(class="input is-danger", autocomplete="email") }}
                                <div class="help is-danger">
                                    {% for error in forgot_password_form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ forgot_password_form.email(class="input", autocomplete="email") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="field mt-4">
                            <div class="control">
                                {{ forgot_password_form.submit(class="button is-primary") }}
                            </div>
                        </div>
                    </form>
                    <hr>
                    <div class="border-top pt-3">
                        <small class="has-text-weight-light">
                            Need an account? <a class="ml-2" href="{{ url_for('security.register') }}">Sign up</a>
                        </small>
                    </div>
                </div>

            </div>
            <div class="column is-hidden-touch"></div>
        </div>
    </div>
</div>
{% endblock content %}

hbhr/templates/security/login_user.html
{% extends "layout.html" %}
{% block content %}
<div class="section">
    <div class="container">
        <br><br>
        <div class="columns">
            <div class="column is-hidden-touch"></div>
            <div class="column is-three-fifths-desktop">
                {% include 'messages.html' %}
                <div class="box is-fullwidth">
                    <form action="{{ url_for_security('login') }}" method="post" name="login_user_form">
                        {{ login_user_form.hidden_tag() }}
                        <fieldset>
                            <legend class="is-size-3 mb-3 is-fullwidth">Log in </legend>
                            <div class="field">
                                {{ login_user_form.email.label(class="label") }}
                                {% if login_user_form.email.errors %}
                                <p class="control has-icons-left">
                                    {{ login_user_form.email(class="input is-danger", autocomplete="username") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </p>
                                <p class="help is-danger">
                                    {% for error in login_user_form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </p>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ login_user_form.email(class="input", autocomplete="username") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                            <div class="field">
                                {{ login_user_form.password.label(class="label") }}
                                {% if login_user_form.password.errors %}
                                <p class="control has-icons-left">
                                    {{ login_user_form.password(class="input is-danger",
                                    autocomplete="current-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                <div class="help is-danger">
                                    {% for error in login_user_form.password.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ login_user_form.password(class="input", autocomplete="current-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                            <div class="field">
                                <div class="control">
                                    <label class="checkbox">
                                        {{ login_user_form.remember(class="form-check-input") }}
                                        {{ login_user_form.remember.label(class="form-check-label") }}
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                        <div class="field mt-2">
                            <div class="control">
                                {{ login_user_form.submit(class="button is-primary") }}
                            </div>

                            <div class="is-size-6 is-family-secondary has-text-weight-light has-text-right mt-3">
                                <a href="{{ url_for('security.forgot_password') }}">Forgot password?</a>
                            </div>
                        </div>
                    </form>
                    <hr>
                    <div class="border-top pt-3">
                        <small class="has-text-weight-light mr-5">
                            Need an account? <a class="ml-2" href="{{ url_for('security.register') }}">Sign up</a>
                        </small> 
                        <small class="has-text-weight-light">
                            Need confirmation? <a class="ml-2" href="{{ url_for('security.send_confirmation') }}">Confirm email</a>
                        </small>
                    </div>
                </div>

            </div>
            <div class="column is-hidden-touch"></div>
        </div>
    </div>
</div>
{% endblock content %}

hbhr/templates/security/register_user.html
{% extends "layout.html" %}
{% block content %}

<div class="section">
    <div class="container">
        <br><br>
        <div class="columns">
            <div class="column is-hidden-touch"></div>
            <div class="column is-three-fifths-desktop">
                {% include 'messages.html' %}
                <div class="box">
                    <form action="{{ url_for_security('register') }}" method="post" name="register_user_form">
                        {{ register_user_form.hidden_tag() }}
                        <fieldset>
                            <legend class="is-size-3 mb-3">Create an account</legend>
                            <div class="field">
                                {{ register_user_form.username.label(class="label") }}

                                {% if register_user_form.username.errors %}
                                <p class="control has-icons-left">
                                    <input class="input is-danger" id="username" name="username" type="text" value="">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-user"></i>
                                    </span>
                                </p>
                                <div class="help is-danger">
                                    {% for error in register_user_form.username.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    <input class="input" id="username" name="username" type="text" value="">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-user"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                            <div class="field">
                                {{ register_user_form.email.label(class="label") }}
                                {% if register_user_form.email.errors %}
                                <p class="control has-icons-left">
                                    {{ register_user_form.email(class="input is-danger", autocomplete="username") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </p>
                                <div class="help is-danger">
                                    {% for error in register_user_form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ register_user_form.email(class="input", autocomplete="username") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </p>
                                {% endif %}
                            </div>
                            <div class="field">
                                {{ register_user_form.password.label(class="label") }}
                                {% if register_user_form.password.errors %}
                                <p class="control has-icons-left">
                                    {{ register_user_form.password(class="input is-danger", autocomplete="new-password")
                                    }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>

                                <div class="help is-danger">
                                    {% for error in register_user_form.password.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <p class="control has-icons-left">
                                    {{ register_user_form.password(class="input", autocomplete="new-password") }}
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-lock"></i>
                                    </span>
                                </p>

                                {% endif %}
                            </div>
                        </fieldset>
                        <br>
                        <div class="box is-shadowless">
                            <small class="mb-4">By creating an account, you acknowledge that you have read and agree with our 
                                <a href="{{ url_for('main.tos') }}" target="_blank">Terms of Service</a> and 
                                <a href="{{ url_for('main.privacy') }}" target="_blank">Privacy Policy</a>.</small>
                        </div>
                        <div class="field mt-2">
                            <div class="control">
                                {{ register_user_form.submit(class="button is-link") }}
                            </div>
                        </div>
                    </form>
                    <hr>
                    <div class="border-top pt-3">
                        <small class="has-text-weight-light">
                            Already have an account? <a class="ml-2" href="{{ url_for('security.login') }}">Log in</a>
                        </small>
                    </div>
                </div>
            </div>
            <div class="column is-hidden-touch"></div>
        </div>
    </div>
</div>
{% endblock content %}